spring.application.name=job-service
server.port=${SERVER_PORT:8081}
application.security.jwt.secret-key=${APPLICATION_SECURITY_JWT_SECRET_KEY:c2VjdXJlLWJhc2U2NC1zZWNyZXQtbWFrZS10aGlzLWxvbmdlci1mb3ItamV3dC1hdXRoLXNlcnZpY2UtMTIzNDU2Nzg5}
application.security.jwt.expiration=${APPLICATION_SECURITY_JWT_EXPIRATION:86400000}
# Database Configuration
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://mysql:3306/ai_hiring_jobs}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Harsh@101845}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect