CREATE TABLE IF NOT EXISTS applications (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    job_id BIGINT NOT NULL,
    candidate_id VARCHAR(255) NOT NULL,
    candidate_email VARCHAR(255),
    resume_path VARCHAR(500),
    resume_status VARCHAR(50) DEFAULT 'PENDING',
    resume_score FLOAT,
    current_round VARCHAR(50) NOT NULL DEFAULT 'RESUME',
    overall_status VARCHAR(50) NOT NULL DEFAULT 'APPLIED',
    aptitude_status VARCHAR(50),
    technical_status VARCHAR(50),
    interview_status VARCHAR(50),
    aptitude_score FLOAT,
    technical_score FLOAT,
    interview_score FLOAT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY unique_job_candidate (job_id, candidate_id),
    INDEX idx_job_id (job_id),
    INDEX idx_candidate_id (candidate_id),
    INDEX idx_candidate_email (candidate_email),
    INDEX idx_overall_status (overall_status),
    INDEX idx_current_round (current_round)
);
