spring.application.name=anti-cheat-service
server.port=${SERVER_PORT:8088}

spring.datasource.url=${ANTICHEAT_DB_URL:jdbc:mysql://mysql:3306/anti_cheat_db}
spring.datasource.username=${ANTICHEAT_DB_USERNAME:root}
spring.datasource.password=${ANTICHEAT_DB_PASSWORD:Harsh@101845}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

spring.jackson.serialization.write-dates-as-timestamps=false

logging.level.org.springframework=INFO
logging.level.com.aihiring.anticheat=INFO