server:
  port: 8082

spring:
  application:
    name: job-service
  datasource:
    url: jdbc:mysql://localhost:3306/ai_hiring_jobs
    username: root
    password: Harsh@101845
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      continue-on-error: false
  jackson:
    serialization:
      write-dates-as-timestamps: false
      
logging:
  level:
    org.springframework.sql.init: DEBUG
    org.hibernate.SQL: DEBUG
 
application:
  security:
    jwt:
      secret-key: "c2VjdXJlLWJhc2U2NC1zZWNyZXQtbWFrZS10aGlzLWxvbmdlci1mb3ItamV3dC1hdXRoLXNlcnZpY2UtMTIzNDU2Nzg5"
      expiration: 86400000