from catalog.common import coding_question

QUESTIONS = [
    coding_question(
        title="Two Sum",
        topic="Arrays",
        difficulty="easy",
        tags=["Array", "HashMap"],
        statement="Given an array of integers nums and an integer target, return the indices of the two numbers such that they add up to target.",
        constraints_text="2 <= nums.length <= 10^5\n-10^9 <= nums[i] <= 10^9\nThere is exactly one solution.",
        input_format="First line contains n\nSecond line contains n space-separated integers\nThird line contains target",
        output_format="Print two indices separated by a space",
        test_cases=[
            {"input_data": "4\n2 7 11 15\n9", "expected_output": "0 1", "hidden": False},
            {"input_data": "5\n3 2 4 8 11\n6", "expected_output": "1 2", "hidden": True},
            {"input_data": "4\n-3 4 3 90\n0", "expected_output": "0 2", "hidden": True},
        ],
        solution_code="""def twoSum(nums, target):\n    seen = {}\n    for i, num in enumerate(nums):\n        need = target - num\n        if need in seen:\n            return [seen[need], i]\n        seen[num] = i\n\n\ndef main():\n    import sys\n    data = sys.stdin.read().strip().split()\n    if not data:\n        return\n    n = int(data[0])\n    nums = list(map(int, data[1:1+n]))\n    target = int(data[1+n])\n    ans = twoSum(nums, target)\n    print(ans[0], ans[1])\n\n\nif __name__ == '__main__':\n    main()\n""",
    ),
    coding_question(
        title="Best Time to Buy and Sell Stock",
        topic="Arrays",
        difficulty="easy",
        tags=["Array", "Greedy"],
        statement="Given an array prices where prices[i] is the price of a stock on the ith day, return the maximum profit from one buy and one sell.",
        constraints_text="1 <= prices.length <= 10^5\n0 <= prices[i] <= 10^4",
        input_format="First line contains n\nSecond line contains n space-separated prices",
        output_format="Print the maximum profit",
        test_cases=[
            {"input_data": "6\n7 1 5 3 6 4", "expected_output": "5", "hidden": False},
            {"input_data": "5\n7 6 4 3 1", "expected_output": "0", "hidden": True},
            {"input_data": "5\n1 2 3 4 5", "expected_output": "4", "hidden": True},
        ],
        solution_code="""def maxProfit(prices):\n    best = 0\n    low = prices[0]\n    for price in prices[1:]:\n        best = max(best, price - low)\n        low = min(low, price)\n    return best\n\n\ndef main():\n    import sys\n    data = list(map(int, sys.stdin.read().strip().split()))\n    if not data:\n        return\n    n = data[0]\n    prices = data[1:1+n]\n    print(maxProfit(prices))\n\n\nif __name__ == '__main__':\n    main()\n""",
    ),
    coding_question(
        title="Maximum Subarray",
        topic="Arrays",
        difficulty="medium",
        tags=["Array", "Dynamic Programming"],
        statement="Given an integer array nums, find the contiguous subarray with the largest sum, and return its sum.",
        constraints_text="1 <= nums.length <= 10^5\n-10^4 <= nums[i] <= 10^4",
        input_format="First line contains n\nSecond line contains n space-separated integers",
        output_format="Print the maximum subarray sum",
        test_cases=[
            {"input_data": "9\n-2 1 -3 4 -1 2 1 -5 4", "expected_output": "6", "hidden": False},
            {"input_data": "5\n1 2 3 4 5", "expected_output": "15", "hidden": True},
            {"input_data": "5\n-1 -2 -3 -4 -5", "expected_output": "-1", "hidden": True},
        ],
        solution_code="""def maxSubArray(nums):\n    current = best = nums[0]\n    for num in nums[1:]:\n        current = max(num, current + num)\n        best = max(best, current)\n    return best\n\n\ndef main():\n    import sys\n    data = list(map(int, sys.stdin.read().strip().split()))\n    if not data:\n        return\n    n = data[0]\n    nums = data[1:1+n]\n    print(maxSubArray(nums))\n\n\nif __name__ == '__main__':\n    main()\n""",
    ),
    coding_question(
        title="Product of Array Except Self",
        topic="Arrays",
        difficulty="medium",
        tags=["Array", "Prefix", "Suffix"],
        statement="Given an integer array nums, return an array answer such that answer[i] is equal to the product of all the elements of nums except nums[i].",
        constraints_text="2 <= nums.length <= 10^5\n-30 <= nums[i] <= 30\nThe product of any prefix or suffix fits in 32-bit integer.",
        input_format="First line contains n\nSecond line contains n space-separated integers",
        output_format="Print the resulting array on one line",
        test_cases=[
            {"input_data": "4\n1 2 3 4", "expected_output": "24 12 8 6", "hidden": False},
            {"input_data": "5\n2 3 4 5 6", "expected_output": "360 240 180 144 120", "hidden": True},
            {"input_data": "3\n0 4 5", "expected_output": "20 0 0", "hidden": True},
        ],
        solution_code="""def productExceptSelf(nums):\n    n = len(nums)\n    answer = [1] * n\n    prefix = 1\n    for i in range(n):\n        answer[i] = prefix\n        prefix *= nums[i]\n    suffix = 1\n    for i in range(n - 1, -1, -1):\n        answer[i] *= suffix\n        suffix *= nums[i]\n    return answer\n\n\ndef main():\n    import sys\n    data = list(map(int, sys.stdin.read().strip().split()))\n    if not data:\n        return\n    n = data[0]\n    nums = data[1:1+n]\n    print(' '.join(map(str, productExceptSelf(nums))))\n\n\nif __name__ == '__main__':\n    main()\n""",
    ),
    coding_question(
        title="Trapping Rain Water",
        topic="Arrays",
        difficulty="hard",
        tags=["Array", "Two Pointers"],
        statement="Given n non-negative integers representing an elevation map where the width of each bar is 1, compute how much water it can trap after raining.",
        constraints_text="1 <= n <= 10^5\n0 <= height[i] <= 10^5",
        input_format="First line contains n\nSecond line contains n heights",
        output_format="Print the total trapped water",
        test_cases=[
            {"input_data": "12\n0 1 0 2 1 0 1 3 2 1 2 1", "expected_output": "6", "hidden": False},
            {"input_data": "6\n4 2 0 3 2 5", "expected_output": "9", "hidden": True},
            {"input_data": "4\n1 2 3 4", "expected_output": "0", "hidden": True},
        ],
        solution_code="""def trap(height):\n    left = 0\n    right = len(height) - 1\n    left_max = right_max = 0\n    trapped = 0\n    while left < right:\n        if height[left] < height[right]:\n            left_max = max(left_max, height[left])\n            trapped += left_max - height[left]\n            left += 1\n        else:\n            right_max = max(right_max, height[right])\n            trapped += right_max - height[right]\n            right -= 1\n    return trapped\n\n\ndef main():\n    import sys\n    data = list(map(int, sys.stdin.read().strip().split()))\n    if not data:\n        return\n    n = data[0]\n    height = data[1:1+n]\n    print(trap(height))\n\n\nif __name__ == '__main__':\n    main()\n""",
    ),
    coding_question(
        title="First Missing Positive",
        topic="Arrays",
        difficulty="hard",
        tags=["Array", "HashSet"],
        statement="Given an unsorted integer array nums, return the smallest missing positive integer.",
        constraints_text="1 <= nums.length <= 10^5\n-2^31 <= nums[i] <= 2^31 - 1",
        input_format="First line contains n\nSecond line contains n space-separated integers",
        output_format="Print the smallest missing positive integer",
        test_cases=[
            {"input_data": "4\n1 2 0 4", "expected_output": "3", "hidden": False},
            {"input_data": "3\n3 4 -1", "expected_output": "1", "hidden": True},
            {"input_data": "5\n7 8 9 11 12", "expected_output": "1", "hidden": True},
        ],
        solution_code="""def firstMissingPositive(nums):\n    n = len(nums)\n    for i in range(n):\n        while 1 <= nums[i] <= n and nums[nums[i] - 1] != nums[i]:\n            j = nums[i] - 1\n            nums[i], nums[j] = nums[j], nums[i]\n    for i, num in enumerate(nums):\n        if num != i + 1:\n            return i + 1\n    return n + 1\n\n\ndef main():\n    import sys\n    data = list(map(int, sys.stdin.read().strip().split()))\n    if not data:\n        return\n    n = data[0]\n    nums = data[1:1+n]\n    print(firstMissingPositive(nums))\n\n\nif __name__ == '__main__':\n    main()\n""",
    ),
]
