from catalog.common import coding_question

QUESTIONS = [
    coding_question(
        title="Binary Search",
        topic="Binary Search",
        difficulty="easy",
        tags=["Binary Search", "Array"],
        statement="Given a sorted array of integers nums and a target value, return the index of target or -1 if it is not found.",
        constraints_text="1 <= nums.length <= 10^5\nnums is sorted in ascending order.",
        input_format="First line contains n\nSecond line contains sorted integers\nThird line contains target",
        output_format="Print the index or -1",
        test_cases=[
            {"input_data": "6\n-1 0 3 5 9 12\n9", "expected_output": "4", "hidden": False},
            {"input_data": "5\n1 2 3 4 5\n6", "expected_output": "-1", "hidden": True},
            {"input_data": "1\n5\n5", "expected_output": "0", "hidden": True},
        ],
        solution_code="""def search(nums, target):\n    left, right = 0, len(nums) - 1\n    while left <= right:\n        mid = (left + right) // 2\n        if nums[mid] == target:\n            return mid\n        if nums[mid] < target:\n            left = mid + 1\n        else:\n            right = mid - 1\n    return -1\n\n\ndef main():\n    import sys\n    data = list(map(int, sys.stdin.read().strip().split()))\n    if not data:\n        return\n    n = data[0]\n    nums = data[1:1+n]\n    target = data[1+n]\n    print(search(nums, target))\n\n\nif __name__ == '__main__':\n    main()\n""",
    ),
    coding_question(
        title="Sqrt(x)",
        topic="Binary Search",
        difficulty="easy",
        tags=["Binary Search", "Math"],
        statement="Given a non-negative integer x, compute and return the square root of x rounded down to the nearest integer.",
        constraints_text="0 <= x <= 2^31 - 1",
        input_format="Single line integer x",
        output_format="Print floor(sqrt(x))",
        test_cases=[
            {"input_data": "8", "expected_output": "2", "hidden": False},
            {"input_data": "0", "expected_output": "0", "hidden": True},
            {"input_data": "2147395599", "expected_output": "46339", "hidden": True},
        ],
        solution_code="""def mySqrt(x):\n    if x < 2:\n        return x\n    left, right = 1, x // 2\n    while left <= right:\n        mid = (left + right) // 2\n        sq = mid * mid\n        if sq == x:\n            return mid\n        if sq < x:\n            left = mid + 1\n        else:\n            right = mid - 1\n    return right\n\n\ndef main():\n    import sys\n    x = int(sys.stdin.read().strip() or 0)\n    print(mySqrt(x))\n\n\nif __name__ == '__main__':\n    main()\n""",
    ),
    coding_question(
        title="Search in Rotated Sorted Array",
        topic="Binary Search",
        difficulty="medium",
        tags=["Binary Search", "Array"],
        statement="Given an integer array nums sorted in ascending order and rotated at some pivot, return the index of target or -1 if it is not present.",
        constraints_text="1 <= nums.length <= 5000\nAll values in nums are unique.",
        input_format="First line contains n\nSecond line contains rotated array\nThird line contains target",
        output_format="Print the index or -1",
        test_cases=[
            {"input_data": "7\n4 5 6 7 0 1 2\n0", "expected_output": "4", "hidden": False},
            {"input_data": "7\n4 5 6 7 0 1 2\n3", "expected_output": "-1", "hidden": True},
            {"input_data": "5\n6 7 1 2 4\n2", "expected_output": "3", "hidden": True},
        ],
        solution_code="""def search(nums, target):\n    left, right = 0, len(nums) - 1\n    while left <= right:\n        mid = (left + right) // 2\n        if nums[mid] == target:\n            return mid\n        if nums[left] <= nums[mid]:\n            if nums[left] <= target < nums[mid]:\n                right = mid - 1\n            else:\n                left = mid + 1\n        else:\n            if nums[mid] < target <= nums[right]:\n                left = mid + 1\n            else:\n                right = mid - 1\n    return -1\n\n\ndef main():\n    import sys\n    data = list(map(int, sys.stdin.read().strip().split()))\n    if not data:\n        return\n    n = data[0]\n    nums = data[1:1+n]\n    target = data[1+n]\n    print(search(nums, target))\n\n\nif __name__ == '__main__':\n    main()\n""",
    ),
    coding_question(
        title="Find Peak Element",
        topic="Binary Search",
        difficulty="medium",
        tags=["Binary Search", "Array"],
        statement="Given an integer array nums, find a peak element and return its index. A peak element is greater than its neighbors.",
        constraints_text="1 <= nums.length <= 1000\nnums[i] != nums[i + 1]",
        input_format="First line contains n\nSecond line contains array elements",
        output_format="Print any peak index",
        test_cases=[
            {"input_data": "4\n1 2 3 1", "expected_output": "2", "hidden": False},
            {"input_data": "2\n1 2", "expected_output": "1", "hidden": True},
            {"input_data": "5\n1 3 5 4 2", "expected_output": "2", "hidden": True},
        ],
        solution_code="""def findPeakElement(nums):\n    left, right = 0, len(nums) - 1\n    while left < right:\n        mid = (left + right) // 2\n        if nums[mid] < nums[mid + 1]:\n            left = mid + 1\n        else:\n            right = mid\n    return left\n\n\ndef main():\n    import sys\n    data = list(map(int, sys.stdin.read().strip().split()))\n    if not data:\n        return\n    n = data[0]\n    nums = data[1:1+n]\n    print(findPeakElement(nums))\n\n\nif __name__ == '__main__':\n    main()\n""",
    ),
    coding_question(
        title="Median of Two Sorted Arrays",
        topic="Binary Search",
        difficulty="hard",
        tags=["Binary Search", "Array"],
        statement="Given two sorted arrays nums1 and nums2, return the median of the two sorted arrays.",
        constraints_text="1 <= nums1.length + nums2.length <= 2000\nArrays are sorted in non-decreasing order.",
        input_format="First line contains n1\nSecond line contains nums1\nThird line contains n2\nFourth line contains nums2",
        output_format="Print the median as a decimal number",
        test_cases=[
            {"input_data": "2\n1 3\n1\n2", "expected_output": "2.0", "hidden": False},
            {"input_data": "2\n1 2\n2\n3 4", "expected_output": "2.5", "hidden": True},
            {"input_data": "0\n\n1\n1", "expected_output": "1.0", "hidden": True},
        ],
        solution_code="""def findMedianSortedArrays(nums1, nums2):\n    if len(nums1) > len(nums2):\n        nums1, nums2 = nums2, nums1\n    m, n = len(nums1), len(nums2)\n    total = m + n\n    half = total // 2\n    left, right = 0, m\n    while True:\n        i = (left + right) // 2\n        j = half - i\n        left_a = nums1[i - 1] if i > 0 else float('-inf')\n        right_a = nums1[i] if i < m else float('inf')\n        left_b = nums2[j - 1] if j > 0 else float('-inf')\n        right_b = nums2[j] if j < n else float('inf')\n        if left_a <= right_b and left_b <= right_a:\n            if total % 2:\n                return float(min(right_a, right_b))\n            return (max(left_a, left_b) + min(right_a, right_b)) / 2\n        if left_a > right_b:\n            right = i - 1\n        else:\n            left = i + 1\n\n\ndef main():\n    import sys\n    data = sys.stdin.read().strip().split()\n    if not data:\n        return\n    idx = 0\n    n1 = int(data[idx]); idx += 1\n    nums1 = list(map(int, data[idx:idx+n1])); idx += n1\n    n2 = int(data[idx]); idx += 1\n    nums2 = list(map(int, data[idx:idx+n2]))\n    print(findMedianSortedArrays(nums1, nums2))\n\n\nif __name__ == '__main__':\n    main()\n""",
    ),
    coding_question(
        title="Split Array Largest Sum",
        topic="Binary Search",
        difficulty="hard",
        tags=["Binary Search", "Prefix Sum"],
        statement="Given an array nums and an integer m, split nums into m non-empty continuous subarrays so that the largest sum among these subarrays is minimized.",
        constraints_text="1 <= nums.length <= 1000\n1 <= m <= min(50, nums.length)",
        input_format="First line contains n\nSecond line contains array elements\nThird line contains m",
        output_format="Print the minimized largest sum",
        test_cases=[
            {"input_data": "5\n7 2 5 10 8\n2", "expected_output": "18", "hidden": False},
            {"input_data": "9\n1 2 3 4 5 6 7 8 9\n3", "expected_output": "17", "hidden": True},
            {"input_data": "4\n1 4 4\n3", "expected_output": "4", "hidden": True},
        ],
        solution_code="""def splitArray(nums, m):\n    left, right = max(nums), sum(nums)\n    def can(limit):\n        parts = 1\n        total = 0\n        for num in nums:\n            if total + num > limit:\n                parts += 1\n                total = num\n            else:\n                total += num\n        return parts <= m\n    while left < right:\n        mid = (left + right) // 2\n        if can(mid):\n            right = mid\n        else:\n            left = mid + 1\n    return left\n\n\ndef main():\n    import sys\n    data = list(map(int, sys.stdin.read().strip().split()))\n    if not data:\n        return\n    n = data[0]\n    nums = data[1:1+n]\n    m = data[1+n]\n    print(splitArray(nums, m))\n\n\nif __name__ == '__main__':\n    main()\n""",
    ),
]
