from catalog.common import coding_question

QUESTIONS = [
    coding_question(
        title="Valid Parentheses",
        topic="Stack",
        difficulty="easy",
        tags=["Stack", "String"],
        statement="Given a string s containing just the characters '(', ')', '{', '}', '[' and ']', determine if the input string is valid.",
        constraints_text="1 <= s.length <= 10^4",
        input_format="Single line string",
        output_format="Print true or false",
        test_cases=[
            {"input_data": "()[]{}", "expected_output": "true", "hidden": False},
            {"input_data": "(]", "expected_output": "false", "hidden": True},
            {"input_data": "([{}])", "expected_output": "true", "hidden": True},
        ],
        solution_code="""def isValid(s):\n    stack = []\n    pairs = {')': '(', ']': '[', '}': '{'}\n    for ch in s:\n        if ch in pairs:\n            if not stack or stack.pop() != pairs[ch]:\n                return False\n        else:\n            stack.append(ch)\n    return not stack\n\n\ndef main():\n    import sys\n    s = sys.stdin.read().strip()\n    print(str(isValid(s)).lower())\n\n\nif __name__ == '__main__':\n    main()\n""",
    ),
    coding_question(
        title="Implement Stack using Queues",
        topic="Stack",
        difficulty="easy",
        tags=["Stack", "Queue"],
        statement="Implement a last-in-first-out (LIFO) stack using only two queues.",
        constraints_text="You must use two queues and support push, pop, top, and empty operations.",
        input_format="First line contains q\nNext q lines contain commands: push x, pop, top, empty",
        output_format="Print outputs for pop/top/empty operations in order",
        test_cases=[
            {"input_data": "6\npush 1\npush 2\ntop\npop\nempty\ntop", "expected_output": "2\n2\nfalse\n1", "hidden": False},
            {"input_data": "4\npush 5\npush 7\npop\nempty", "expected_output": "7\nfalse", "hidden": True},
            {"input_data": "3\nempty\npush 9\ntop", "expected_output": "true\n9", "hidden": True},
        ],
        solution_code="""from collections import deque\n\n\nclass MyStack:\n    def __init__(self):\n        self.q1 = deque()\n        self.q2 = deque()\n\n    def push(self, x):\n        self.q2.append(x)\n        while self.q1:\n            self.q2.append(self.q1.popleft())\n        self.q1, self.q2 = self.q2, self.q1\n\n    def pop(self):\n        return self.q1.popleft()\n\n    def top(self):\n        return self.q1[0]\n\n    def empty(self):\n        return not self.q1\n\n\ndef main():\n    import sys\n    lines = sys.stdin.read().strip().splitlines()\n    if not lines:\n        return\n    q = int(lines[0])\n    stack = MyStack()\n    output = []\n    for line in lines[1:1+q]:\n        parts = line.split()\n        if parts[0] == 'push':\n            stack.push(int(parts[1]))\n        elif parts[0] == 'pop':\n            output.append(str(stack.pop()))\n        elif parts[0] == 'top':\n            output.append(str(stack.top()))\n        else:\n            output.append(str(stack.empty()).lower())\n    print('\n'.join(output))\n\n\nif __name__ == '__main__':\n    main()\n""",
    ),
    coding_question(
        title="Next Greater Element II",
        topic="Stack",
        difficulty="medium",
        tags=["Stack", "Monotonic Stack"],
        statement="Given a circular integer array nums, return the next greater number for every element.",
        constraints_text="1 <= nums.length <= 10^4",
        input_format="First line contains n\nSecond line contains n space-separated integers",
        output_format="Print the next greater elements array",
        test_cases=[
            {"input_data": "3\n1 2 1", "expected_output": "2 -1 2", "hidden": False},
            {"input_data": "4\n1 2 3 4", "expected_output": "2 3 4 -1", "hidden": True},
            {"input_data": "5\n5 4 3 2 1", "expected_output": "-1 5 5 5 5", "hidden": True},
        ],
        solution_code="""def nextGreaterElements(nums):\n    n = len(nums)\n    answer = [-1] * n\n    stack = []\n    for i in range(2 * n):\n        num = nums[i % n]\n        while stack and nums[stack[-1]] < num:\n            answer[stack.pop()] = num\n        if i < n:\n            stack.append(i)\n    return answer\n\n\ndef main():\n    import sys\n    data = list(map(int, sys.stdin.read().strip().split()))\n    if not data:\n        return\n    n = data[0]\n    nums = data[1:1+n]\n    print(' '.join(map(str, nextGreaterElements(nums))))\n\n\nif __name__ == '__main__':\n    main()\n""",
    ),
    coding_question(
        title="Decode String",
        topic="Stack",
        difficulty="medium",
        tags=["Stack", "String"],
        statement="Given an encoded string, return its decoded string. The encoding rule is k[encoded_string].",
        constraints_text="The input is always valid and contains digits, letters, and brackets only.",
        input_format="Single line encoded string",
        output_format="Print the decoded string",
        test_cases=[
            {"input_data": "3[a2[c]]", "expected_output": "accaccacc", "hidden": False},
            {"input_data": "2[abc]3[cd]ef", "expected_output": "abcabccdcdcdef", "hidden": True},
            {"input_data": "10[a]", "expected_output": "aaaaaaaaaa", "hidden": True},
        ],
        solution_code="""def decodeString(s):\n    count_stack = []\n    string_stack = []\n    current = ''\n    count = 0\n    for ch in s:\n        if ch.isdigit():\n            count = count * 10 + int(ch)\n        elif ch == '[':\n            count_stack.append(count)\n            string_stack.append(current)\n            count = 0\n            current = ''\n        elif ch == ']':\n            current = string_stack.pop() + current * count_stack.pop()\n        else:\n            current += ch\n    return current\n\n\ndef main():\n    import sys\n    s = sys.stdin.read().strip()\n    print(decodeString(s))\n\n\nif __name__ == '__main__':\n    main()\n""",
    ),
    coding_question(
        title="Largest Rectangle in Histogram",
        topic="Stack",
        difficulty="hard",
        tags=["Stack", "Monotonic Stack"],
        statement="Given an array of integers heights representing the histogram's bar height where the width of each bar is 1, return the area of the largest rectangle in the histogram.",
        constraints_text="1 <= heights.length <= 10^5\n0 <= heights[i] <= 10^4",
        input_format="First line contains n\nSecond line contains histogram heights",
        output_format="Print the maximum area",
        test_cases=[
            {"input_data": "6\n2 1 5 6 2 3", "expected_output": "10", "hidden": False},
            {"input_data": "2\n2 4", "expected_output": "4", "hidden": True},
            {"input_data": "5\n6 2 5 4 5", "expected_output": "12", "hidden": True},
        ],
        solution_code="""def largestRectangleArea(heights):\n    stack = []\n    best = 0\n    heights.append(0)\n    for i, h in enumerate(heights):\n        while stack and heights[stack[-1]] > h:\n            height = heights[stack.pop()]\n            left = stack[-1] if stack else -1\n            best = max(best, height * (i - left - 1))\n        stack.append(i)\n    heights.pop()\n    return best\n\n\ndef main():\n    import sys\n    data = list(map(int, sys.stdin.read().strip().split()))\n    if not data:\n        return\n    n = data[0]\n    heights = data[1:1+n]\n    print(largestRectangleArea(heights))\n\n\nif __name__ == '__main__':\n    main()\n""",
    ),
    coding_question(
        title="Maximal Rectangle",
        topic="Stack",
        difficulty="hard",
        tags=["Stack", "Dynamic Programming"],
        statement="Given a binary matrix filled with 0's and 1's, find the largest rectangle containing only 1's and return its area.",
        constraints_text="1 <= rows, cols <= 200",
        input_format="First line contains r and c\nNext r lines contain c binary values separated by spaces",
        output_format="Print the maximum rectangle area",
        test_cases=[
            {"input_data": "4 5\n1 0 1 0 0\n1 0 1 1 1\n1 1 1 1 1\n1 0 0 1 0", "expected_output": "6", "hidden": False},
            {"input_data": "2 2\n1 1\n1 1", "expected_output": "4", "hidden": True},
            {"input_data": "1 4\n0 1 1 0", "expected_output": "2", "hidden": True},
        ],
        solution_code="""def largestRectangleArea(heights):\n    stack = []\n    best = 0\n    heights.append(0)\n    for i, h in enumerate(heights):\n        while stack and heights[stack[-1]] > h:\n            height = heights[stack.pop()]\n            left = stack[-1] if stack else -1\n            best = max(best, height * (i - left - 1))\n        stack.append(i)\n    heights.pop()\n    return best\n\n\ndef maximalRectangle(matrix):\n    if not matrix:\n        return 0\n    cols = len(matrix[0])\n    heights = [0] * cols\n    best = 0\n    for row in matrix:\n        for i, value in enumerate(row):\n            heights[i] = heights[i] + 1 if value == '1' or value == 1 else 0\n        best = max(best, largestRectangleArea(heights[:]))\n    return best\n\n\ndef main():\n    import sys\n    lines = sys.stdin.read().strip().splitlines()\n    if not lines:\n        return\n    r, c = map(int, lines[0].split())\n    matrix = [lines[i + 1].split() for i in range(r)]\n    print(maximalRectangle(matrix))\n\n\nif __name__ == '__main__':\n    main()\n""",
    ),
]
