from catalog.common import coding_question

QUESTIONS = [
    coding_question(
        title="Valid Anagram",
        topic="Strings",
        difficulty="easy",
        tags=["String", "HashMap"],
        statement="Given two strings s and t, return true if t is an anagram of s, and false otherwise.",
        constraints_text="1 <= s.length, t.length <= 5 * 10^4\nStrings contain lowercase English letters only.",
        input_format="First line contains s\nSecond line contains t",
        output_format="Print true or false",
        test_cases=[
            {"input_data": "anagram\nnaagram", "expected_output": "false", "hidden": False},
            {"input_data": "anagram\nnagaram", "expected_output": "true", "hidden": True},
            {"input_data": "rat\ncar", "expected_output": "false", "hidden": True},
        ],
        solution_code="""from collections import Counter\n\n\ndef isAnagram(s, t):\n    return Counter(s) == Counter(t)\n\n\ndef main():\n    import sys\n    lines = sys.stdin.read().splitlines()\n    if len(lines) < 2:\n        return\n    print(str(isAnagram(lines[0].strip(), lines[1].strip())).lower())\n\n\nif __name__ == '__main__':\n    main()\n""",
    ),
    coding_question(
        title="Valid Palindrome",
        topic="Strings",
        difficulty="easy",
        tags=["String", "Two Pointers"],
        statement="Given a string s, return true if it is a palindrome, considering only alphanumeric characters and ignoring cases.",
        constraints_text="1 <= s.length <= 2 * 10^5\nString may contain spaces and punctuation.",
        input_format="Single line string",
        output_format="Print true or false",
        test_cases=[
            {"input_data": "A man, a plan, a canal: Panama", "expected_output": "true", "hidden": False},
            {"input_data": "race a car", "expected_output": "false", "hidden": True},
            {"input_data": "No lemon, no melon", "expected_output": "true", "hidden": True},
        ],
        solution_code="""def isPalindrome(s):\n    filtered = [ch.lower() for ch in s if ch.isalnum()]\n    return filtered == filtered[::-1]\n\n\ndef main():\n    import sys\n    s = sys.stdin.read().rstrip('\n')\n    print(str(isPalindrome(s)).lower())\n\n\nif __name__ == '__main__':\n    main()\n""",
    ),
    coding_question(
        title="Longest Substring Without Repeating Characters",
        topic="Strings",
        difficulty="medium",
        tags=["String", "Sliding Window"],
        statement="Given a string s, find the length of the longest substring without repeating characters.",
        constraints_text="0 <= s.length <= 5 * 10^4\nString may contain any ASCII characters.",
        input_format="Single line string",
        output_format="Print the maximum length",
        test_cases=[
            {"input_data": "abcabcbb", "expected_output": "3", "hidden": False},
            {"input_data": "bbbbb", "expected_output": "1", "hidden": True},
            {"input_data": "pwwkew", "expected_output": "3", "hidden": True},
        ],
        solution_code="""def lengthOfLongestSubstring(s):\n    seen = {}\n    left = 0\n    best = 0\n    for right, ch in enumerate(s):\n        if ch in seen and seen[ch] >= left:\n            left = seen[ch] + 1\n        seen[ch] = right\n        best = max(best, right - left + 1)\n    return best\n\n\ndef main():\n    import sys\n    s = sys.stdin.read().rstrip('\n')\n    print(lengthOfLongestSubstring(s))\n\n\nif __name__ == '__main__':\n    main()\n""",
    ),
    coding_question(
        title="Group Anagrams",
        topic="Strings",
        difficulty="medium",
        tags=["String", "HashMap"],
        statement="Given an array of strings, group the anagrams together. Return the groups sorted by the first item in each group and each group sorted lexicographically.",
        constraints_text="1 <= strings.length <= 10^4\nEach string has length at most 100.",
        input_format="First line contains n\nSecond line contains n space-separated strings",
        output_format="Print groups using | between groups and , between items in a group",
        test_cases=[
            {"input_data": "6\neat tea tan ate nat bat", "expected_output": "ate,eat,tea|bat|nat,tan", "hidden": False},
            {"input_data": "4\nabc bca cab foo", "expected_output": "abc,bca,cab|foo", "hidden": True},
            {"input_data": "3\nlisten silent enlist", "expected_output": "enlist,listen,silent", "hidden": True},
        ],
        solution_code="""from collections import defaultdict\n\n\ndef groupAnagrams(strs):\n    groups = defaultdict(list)\n    for word in strs:\n        groups[''.join(sorted(word))].append(word)\n    result = [sorted(group) for group in groups.values()]\n    result.sort(key=lambda group: group[0])\n    return result\n\n\ndef main():\n    import sys\n    data = sys.stdin.read().strip().split()\n    if not data:\n        return\n    n = int(data[0])\n    words = data[1:1+n]\n    groups = groupAnagrams(words)\n    print('|'.join(','.join(group) for group in groups))\n\n\nif __name__ == '__main__':\n    main()\n""",
    ),
    coding_question(
        title="Minimum Window Substring",
        topic="Strings",
        difficulty="hard",
        tags=["String", "Sliding Window"],
        statement="Given two strings s and t, return the minimum window substring of s such that every character in t is included in the window.",
        constraints_text="1 <= s.length, t.length <= 10^5\nCharacters are ASCII letters only.",
        input_format="First line contains s\nSecond line contains t",
        output_format="Print the minimum window substring",
        test_cases=[
            {"input_data": "ADOBECODEBANC\nABC", "expected_output": "BANC", "hidden": False},
            {"input_data": "a\na", "expected_output": "a", "hidden": True},
            {"input_data": "a\naa", "expected_output": "", "hidden": True},
        ],
        solution_code="""from collections import Counter\n\n\ndef minWindow(s, t):\n    need = Counter(t)\n    missing = len(t)\n    left = start = end = 0\n    for right, ch in enumerate(s, 1):\n        if need[ch] > 0:\n            missing -= 1\n        need[ch] -= 1\n        if missing == 0:\n            while left < right and need[s[left]] < 0:\n                need[s[left]] += 1\n                left += 1\n            if end == 0 or right - left < end - start:\n                start, end = left, right\n            need[s[left]] += 1\n            missing += 1\n            left += 1\n    return s[start:end]\n\n\ndef main():\n    import sys\n    lines = sys.stdin.read().splitlines()\n    if len(lines) < 2:\n        return\n    print(minWindow(lines[0].strip(), lines[1].strip()))\n\n\nif __name__ == '__main__':\n    main()\n""",
    ),
    coding_question(
        title="Palindrome Partitioning II",
        topic="Strings",
        difficulty="hard",
        tags=["String", "Dynamic Programming"],
        statement="Given a string s, partition s such that every substring is a palindrome. Return the minimum cuts needed.",
        constraints_text="1 <= s.length <= 2000\nString contains lowercase letters only.",
        input_format="Single line string",
        output_format="Print the minimum number of cuts",
        test_cases=[
            {"input_data": "aab", "expected_output": "1", "hidden": False},
            {"input_data": "a", "expected_output": "0", "hidden": True},
            {"input_data": "abccbc", "expected_output": "2", "hidden": True},
        ],
        solution_code="""def minCut(s):\n    n = len(s)\n    is_pal = [[False] * n for _ in range(n)]\n    cuts = [0] * n\n    for end in range(n):\n        best = end\n        for start in range(end + 1):\n            if s[start] == s[end] and (end - start <= 1 or is_pal[start + 1][end - 1]):\n                is_pal[start][end] = True\n                best = 0 if start == 0 else min(best, cuts[start - 1] + 1)\n        cuts[end] = best\n    return cuts[-1]\n\n\ndef main():\n    import sys\n    s = sys.stdin.read().rstrip('\n')\n    print(minCut(s))\n\n\nif __name__ == '__main__':\n    main()\n""",
    ),
]
